name: wt_google_sheets
description: "Dart library that reads and writes data to Google Sheets."
version: 0.0.1
homepage: https://github.com/tmcmaster/wt_google_sheet

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gsheets:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

